Allow for optional assertions on AdvanceTime()
dogmatiq/testkit pull request #112
Opened 2020-10-22 10:13 UTC by jmalloc

Fixes #110 

This PR changes the `assert.Assertion` interface around to allow for an `assert.Optional` interface which is satisfied by all existing assertions as well as the new `assert.Nothing` value.

This allows `AdvanceTime()` to accept an `Optional` instead of an `Assertion`, thus removing the need to allow `nil` assertions which are unclear when seen in tests.

2020-10-22 23:49 UTC, danilvpetrov requested changes
Other than a small grammar comments, I cannot see anything else on this PR that might need correction.

Oh, may be a quick question: these methods allow one  `assert.OptionalAssertion` as well one `assert.Assertion`, right? What tricks me is that the word `optional` might suggest multiple optional assertions. However, I am not that fully familiar with the usage of these assertions so I might be missing a lot concept-wise.

2020-10-22 23:49 UTC, danilvpetrov commented on assert/assertion.go
> +// OptionalAssertion is an interface that accept all Assertion types, as well as
```suggestion
// OptionalAssertion is an interface that accepts all Assertion types, as well as
```

2020-10-22 23:52 UTC, jmalloc commented
> these method allow one `assert.OptionalAssertion` as well one `assert.Assertion`, right?

Yeah, basically any `Assertion` and the `assert.Nothing` value both satisfy the `OptionalAssertion` assertion interface. But `Nothing` does not satisfy `Assertion`.

Neither of them are referring to multiple assertions (unless you use something like `assert.[All|Any|None]Of()`, but even then they are a single assertion that contains other assertions).

2020-10-22 23:53 UTC, danilvpetrov approved these changes

2020-10-23 01:28 UTC, koden-km approved these changes
Looks good, just one grammar issue.

2020-10-23 01:28 UTC, koden-km commented on assert/assertion.go
> +// Nothing is an "optional assertion" that always passes and does not build an
```suggestion
// Nothing is an "optional assertion" that always passes and does not build a
```

2020-10-23 01:29 UTC, jmalloc commented
Thank you gentlemen.

2020-10-23 01:30 UTC, merged