Omit valid nested none of expectations from reports
dogmatiq/testkit pull request #346
Opened 2024-08-13 03:30 UTC by sameaste92

#### What change does this introduce?

Omits valid nested none of expectations from reports

#### Why make this change?

currently if you nest a none of expectation within an `Any Of` of `All Of` expectation and a sibling expectation fails, the `None Of` expectation will still print the expectation messages.

#### Is there anything you are unsure about?

don't think so

#### What issues does this relate to?

2024-08-13 04:20 UTC, sameaste92 commented
Example of current report adding explanation and suggestions to a passing `None Of` expectation when nested:
```shell
    ✗ all of (1 of the expectations failed)
                    ✓ record a specific '*event.BigBlindDeclined' event
                    ✓ record a specific '*event.SatOut' event
                    ✗ record a specific '*event.NextBlindTurnStarted' event
                    
                      | EXPLANATION
                      |     a similar event was recorded by the 'blinds.aggregate' aggregate message handler
                      | 
                      | SUGGESTIONS
                      |     • check the content of the message
                      | 
                      | MESSAGE DIFF
                      |     *event.NextBlindTurnStarted{
                      |         HandId:         "123456789-1"
                      |         TableId:        "deec68f2-ac08-4b1a-8778-4b8f3cf2caf3"
                      |         Seat:           [-4-]{+3+}
                      |         AllowedActions: {
                      |             1
                      |             4
                      |         }
                      |     }
                    ✓ none of
                        ✗ record any '*event.HandCanceled' event
                        
                          | EXPLANATION
                          |     none of the engaged handlers recorded a matching event
                          | 
                          | SUGGESTIONS
                          |     • enable integration handlers using the EnableHandlerType() option
                          |     • verify the logic within the 'blinds.aggregate' aggregate message handler
                        ✗ record any '*event.BlindsComplete' event
                        
                          | EXPLANATION
                          |     none of the engaged handlers recorded a matching event
                          | 
                          | SUGGESTIONS
                          |     • enable integration handlers using the EnableHandlerType() option
                          |     • verify the logic within the 'blinds.aggregate' aggregate message handler
```

2024-08-13 04:44 UTC, sameaste92 commented
Example of current report adding explanation and suggestions to a passing `None Of` expectation when nested:
```shell
    ✗ all of (1 of the expectations failed)
                    ✓ record a specific '*event.EventA' event
                    ✓ record a specific '*event.EventB' event
                    ✗ record a specific '*event.EventC' event
                    
                      | EXPLANATION
                      |     a similar event was recorded by the 'example.aggregate' aggregate message handler
                      | 
                      | SUGGESTIONS
                      |     • check the content of the message
                      | 
                      | MESSAGE DIFF
                      |     *event.EventC{
                      |         Id:         "12345"
                      |     }
                    ✓ none of
                        ✗ record any '*event.EventD' event
                        
                          | EXPLANATION
                          |     none of the engaged handlers recorded a matching event
                          | 
                          | SUGGESTIONS
                          |     • enable integration handlers using the EnableHandlerType() option
                          |     • verify the logic within the 'example.aggregate' aggregate message handler
                        ✗ record any '*event.EventE' event
                        
                          | EXPLANATION
                          |     none of the engaged handlers recorded a matching event
                          | 
                          | SUGGESTIONS
                          |     • enable integration handlers using the EnableHandlerType() option
                          |     • verify the logic within the 'example.aggregate' aggregate message handler
```

2024-08-15 21:53 UTC, jmalloc commented
It took me a while to understand what was going on here, but if I understand correctly the issue doesn't actually require nested composites, it just requires a `NoneOf` with one passing and one failing child.

I've refactored this PR in https://github.com/dogmatiq/testkit/pull/347, which makes each `Expectation` implementation responsible for omitting it's own explanation when it "fails as desired". The reasons for this are twofold:

1. It shifts the responsibility from the rendering layer to the report generation layer
2. It allows us to tailor expectations to negated cases such as `NoneOf`, rather than omitting them entirely

@sameaste92 Any chance you could try out my branch (`omit-valid-nested-none-of-expectations-from-reports-james`) to make sure it covers the problem as you were seeing it? I may need to add more tests for the nested-composites if I've missed something there.

2024-08-15 21:54 UTC, jmalloc commented
/cc @koden-km This and associated PR #347 lay some good groundwork for a `Not()` type wrapper as you suggested.

2024-08-15 21:55 UTC, jmalloc requested changes
See PR #347.

2024-08-15 22:49 UTC, sameaste92 commented
> It took me a while to understand what was going on here, but if I understand correctly the issue doesn't actually require nested composites, it just requires a `NoneOf` with one passing and one failing child.

@jmalloc yeah good catch, I hadn't realised that if you had a failing `NoneOf` the printed explanations were inverted, and had just assumed this was a bug produced by using nested composites

> I've refactored this PR in #347, which makes each `Expectation` implementation responsible for omitting it's own explanation when it "fails as desired". The reasons for this are twofold:
> 
> 1. It shifts the responsibility from the rendering layer to the report generation layer
> 2. It allows us to tailor expectations to negated cases such as `NoneOf`, rather than omitting them entirely

Shifting the responsibility to the generation layer makes a lot more sense, thanks

> @sameaste92 Any chance you could try out my branch (`omit-valid-nested-none-of-expectations-from-reports-james`) to make sure it covers the problem as you were seeing it? I may need to add more tests for the nested-composites if I've missed something there.

Just tested your branch and it works 😄

2024-08-15 22:51 UTC, merged